---
- hosts: all
  sudo: yes

# The following vars will generate these lines in /etc/sudoers.d/testing:
#
# testone  somehost=(vagrant, otheruser) NOPASSWD: /usr/bin/foo, /usr/bin/bar, (root) PASSWD: /usr/bin/baz
# testtwo  somehost=(ALL) PASSWD: /usr/bin/foo
# testthree  somehost=(ALL) PASSWD: /usr/bin/baz
# testfour  ALL=(ALL) PASSWD: ALL

  vars:
    sudoers_filename: "testing"
    sudoers:
      - user: "testone"
        host: "somehost"
        user_commands:
          - runas_users:
              - "vagrant"
              - "otheruser"
            commands:
              - "/usr/bin/foo"
              - "/usr/bin/bar"
            nopasswd: true
          - runas_users:
              - "root"
            commands:
              - "/usr/bin/baz"
            nopasswd: false
      - user: "testtwo"
        host: "somehost"
        user_commands:
          - commands:
              - "/usr/bin/foo"
            nopasswd: false
      - user: "testthree"
        host: "somehost"
        user_commands:
          - nopasswd: false
            commands:
              - "/usr/bin/baz"
      - user: "testfour"

  tasks:
    - name: add test users
      user: name={{ item }} shell=/bin/bash state=present
      with_items:
        - "testone"
        - "testtwo"

  roles:
    - .
